# Generated by Codex on 2026-02-13

from django.conf import settings
from django.db import migrations


def backfill_profiles_and_staff(apps, schema_editor):
    user_app_label, user_model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(user_app_label, user_model_name)
    UserProfile = apps.get_model("core", "UserProfile")

    for user in User.objects.all().iterator():
        UserProfile.objects.get_or_create(
            user_id=user.id,
            defaults={"role": "user"},
        )

    admin_user_ids = UserProfile.objects.filter(role="admin").values_list("user_id", flat=True)
    User.objects.filter(id__in=admin_user_ids, is_superuser=False).update(is_staff=True)


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_analysis_preset"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(backfill_profiles_and_staff, noop_reverse),
    ]
